CREATE SCHEMA COMPANY;

CREATE TABLE EMP(
    SSN CHAR(9)
    first_name VARCHAR(10)
)
CREATE TABLE DEPARTMENT(
    DNAME VARCHAR(10)NOT NULL, 
    DNUMBER INTEGER NOT NULL, 
    MGRSSN CHAR(9), 
    MGRSTARTDATE CHAR(9), 
    PRIMARY KEY (DNUMBER), 
    UNIQUE (DNAME), 
    FOREIGN KEY (MGRSSN) REFERENCES EMP
);